# Generated by Django 3.0.6 on 2020-05-27 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOfLife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='uploads/cv/2020/5/27/')),
                ('image', models.ImageField(upload_to='uploads/cv/images/2020/5/27/')),
                ('title', models.CharField(default='', max_length=100)),
                ('path', models.CharField(default='uploads/cv/2020/5/27/', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CV',
                'verbose_name_plural': 'CVs',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ImageField(upload_to='uploads/images/2020/5/27/')),
                ('name', models.CharField(default='', max_length=100)),
                ('path', models.CharField(default='uploads/images/2020/5/27/', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='PictureCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('pictures', models.ManyToManyField(blank=True, related_name='picture_collection', to='uploads.Picture')),
                ('preview_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='uploads.Picture')),
            ],
        ),
    ]
