# Generated by Django 3.0.6 on 2020-05-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseoflife',
            name='path',
        ),
        migrations.RemoveField(
            model_name='courseoflife',
            name='title',
        ),
        migrations.RemoveField(
            model_name='courseoflife',
            name='upload',
        ),
        migrations.AddField(
            model_name='courseoflife',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='bio'),
        ),
        migrations.AddField(
            model_name='courseoflife',
            name='education',
            field=models.TextField(blank=True, null=True, verbose_name='education'),
        ),
        migrations.AddField(
            model_name='courseoflife',
            name='experience',
            field=models.TextField(blank=True, null=True, verbose_name='work experience'),
        ),
        migrations.AddField(
            model_name='courseoflife',
            name='works',
            field=models.TextField(blank=True, null=True, verbose_name='published works'),
        ),
        migrations.AlterField(
            model_name='courseoflife',
            name='image',
            field=models.ImageField(upload_to='uploads/cv/images/2020/5/28/'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='path',
            field=models.CharField(default='uploads/images/2020/5/28/', max_length=40),
        ),
        migrations.AlterField(
            model_name='picture',
            name='upload',
            field=models.ImageField(upload_to='uploads/images/2020/5/28/'),
        ),
    ]
