# Generated by Django 3.0.6 on 2020-05-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_auto_20200528_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoflife',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
