# Generated by Django 3.0.6 on 2020-08-26 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0006_auto_20200826_1917'),
        ('uploads', '0006_auto_20200826_1919'),
    ]

    operations = [
    ]
