# Generated by Django 3.0.6 on 2020-08-27 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0007_merge_20200826_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoflife',
            name='image',
            field=models.ImageField(upload_to='uploads/cv/images/2020/8/27/'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='path',
            field=models.CharField(default='uploads/images/2020/8/27/', max_length=40),
        ),
        migrations.AlterField(
            model_name='picture',
            name='upload',
            field=models.ImageField(upload_to='uploads/images/2020/8/27/'),
        ),
    ]
